const API = 'https://app.getaptly.com/api/portal/listings/yDgjRcz9hTcv4iav4';
const APTLY_SEARCH = 'https://portal.getaptly.com/search/yDgjRcz9hTcv4iav4/';
let listings = [], map, markers, overviewZoom=10, resetControl, visibleForMap=[];
const compared = new Set();
const $ = s => document.querySelector(s);
const money = cents => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((cents||0)/100);
const esc = value => String(value ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const street = p => p.address?.address || p.address?.streetName || p.marketingName || p.name;
// Action URLs are resolved exclusively from the Aptly feed record. Direct links
// win when Aptly provides them; the tour fallback is the canonical Aptly route
// composed from the record's company and listing identifiers.
const firstFeedUrl = (...values) => values.find(v => typeof v === 'string' && /^https:\/\//.test(v));
const applyUrl = p => firstFeedUrl(p.aptlyScreening?.link,p.links?.apply,p.applyUrl) || APTLY_SEARCH;
const tourUrl = p => firstFeedUrl(p.aptlyShowings?.link,p.aptlyShowings?.url,p.links?.tour,p.tourUrl) || (p.aptlyShowings?.active&&p.companyId&&p._id ? `https://portal.getaptly.com/search/${encodeURIComponent(p.companyId)}/${encodeURIComponent(p._id)}` : APTLY_SEARCH);

function photoDots(index,count){
  const visible=Math.min(5,count), start=Math.max(0,Math.min(index-2,count-visible));
  return Array.from({length:visible},(_,i)=>{const absolute=start+i,edge=(count>visible&&((i===0&&start>0)||(i===visible-1&&start+visible<count)))?' edge':'';return `<i class="${absolute===index?'active':''}${edge}" aria-hidden="true"></i>`}).join('');
}
function photoStatus(index,count){return `<span class="photo-dots">${photoDots(index,count)}</span><span class="photo-number"><b>${index+1}</b>/${count}</span>`}
function mapPreview(p){
  const imgs=photos(p),count=imgs.length||1,img=imgs[0]||'assets/areas.jpg';
  return `<article class="map-property-preview" data-id="${esc(p._id)}" data-photo="0"><div class="map-preview-media"><img src="${esc(img)}" alt="${esc(street(p))}, photo 1 of ${count}"><span class="map-preview-badge">AVAILABLE NOW</span>${count>1?'<button class="map-photo-arrow map-photo-prev" aria-label="Previous property photo">‹</button><button class="map-photo-arrow map-photo-next" aria-label="Next property photo">›</button>':''}<span class="map-photo-status" aria-label="Photo 1 of ${count}">${photoStatus(0,count)}</span></div><div class="map-preview-body"><div class="map-preview-price">${money(p.marketRent?.amount)}<small>/mo</small></div><div class="map-preview-facts"><b>${esc(p.beds??'—')}</b> bd <b>${esc(p.baths??'—')}</b> ba <b>${p.totalArea?Number(p.totalArea).toLocaleString():'—'}</b> sq ft</div><h3>${esc(street(p))}</h3><p>${esc(p.address?.city)}, ${esc(p.address?.stateCode)} ${esc(p.address?.postalCode)}</p><div class="map-preview-actions"><a href="${esc(tourUrl(p))}" target="_blank" rel="noopener">SELF TOUR</a><a class="apply" href="${esc(applyUrl(p))}" target="_blank" rel="noopener">APPLY</a><a class="details" href="rental-detail.html?id=${encodeURIComponent(p._id)}">VIEW DETAILS <span>→</span></a></div></div></article>`;
}

function card(p){
  const img=p.marketingFiles?.[0]||p.photo?.[0]||'assets/areas.jpg';
  const count=p.marketingFiles?.length||p.photo?.length||1;
  return `<article class="property-card${compared.has(p._id)?' comparing':''}" data-id="${esc(p._id)}" data-photo="0"><div class="media"><img loading="lazy" src="${esc(img)}" alt="${esc(street(p))}, photo 1 of ${count}"><span class="badge">AVAILABLE NOW</span>${count>1?'<button class="photo-arrow photo-prev" aria-label="Previous property photo">‹</button><button class="photo-arrow photo-next" aria-label="Next property photo">›</button>':''}<span class="photo-count" aria-label="Photo 1 of ${count}">${photoStatus(0,count)}</span><div class="hover-tools"><button class="share-button">↗<span>SHARE</span></button><button class="compare-button">${compared.has(p._id)?'✓':'＋'}<span>${compared.has(p._id)?'ADDED':'COMPARE'}</span></button></div></div><div class="card-body"><div class="price">${money(p.marketRent?.amount)}<small>/mo</small></div><div class="facts"><span>${esc(p.beds??'—')} bd</span><span>${esc(p.baths??'—')} ba</span><span>${p.totalArea?Number(p.totalArea).toLocaleString():'—'} sq ft</span></div><h3>${esc(street(p))}</h3><div class="address">${esc(p.address?.city)}, ${esc(p.address?.stateCode)} ${esc(p.address?.postalCode)}</div><div class="actions"><a href="${esc(tourUrl(p))}" target="_blank" rel="noopener">Self tour</a><a class="apply" href="${esc(applyUrl(p))}" target="_blank" rel="noopener">Apply</a><a class="details-button" href="rental-detail.html?id=${encodeURIComponent(p._id)}">View details →</a></div></div></article>`;
}

function filtered(){
  const q=$('#query').value.trim().toLowerCase(), bed=Number($('#beds').value||0), type=$('#type').value;
  const [min,max]=($('#rent').value||'0-999999').split('-').map(Number);
  return listings.filter(p=>{const rent=(p.marketRent?.amount||0)/100;const hay=[p.name,p.marketingName,p.address?.address,p.address?.city,p.address?.postalCode].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!bed||p.beds>=bed)&&(!type||p.rentalCategory===type)&&(rent>=min&&rent<=max)});
}

function render(){
  const data=filtered();
  $('#resultCount').textContent=`${data.length} of ${listings.length} homes`;
  $('#listingGrid').innerHTML=data.length?data.map(card).join(''):'<div class="empty"><h3>No homes match those filters.</h3><p>Try broadening your search.</p></div>';
  $('#status').hidden=true;
  document.querySelector('.results-split')?.classList.remove('loading');
  renderMap(data);
}

function initMap(){
  if(!window.L||map)return;
  map=L.map('map',{scrollWheelZoom:false}).setView([31.55,-97.15],11);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
  markers=L.markerClusterGroup({showCoverageOnHover:false,zoomToBoundsOnClick:true,spiderfyOnMaxZoom:true,disableClusteringAtZoom:16,maxClusterRadius:60,iconCreateFunction:c=>L.divIcon({html:`<div><b>${c.getChildCount()}</b><span>HOMES</span></div>`,className:'home-cluster',iconSize:[62,62]})});map.addLayer(markers);markers.on('clusterclick',()=>setTimeout(()=>document.querySelector('.reset-map-control')?.classList.add('visible'),80));
  const Reset=L.Control.extend({options:{position:'topleft'},onAdd(){const box=L.DomUtil.create('div','leaflet-bar reset-map-control');const b=L.DomUtil.create('button','',box);b.type='button';b.innerHTML='↙ SHOW ALL HOMES';b.title='Zoom out to all available homes';L.DomEvent.disableClickPropagation(box);L.DomEvent.on(b,'click',fitAllHomes);return box}});resetControl=new Reset();resetControl.addTo(map);
  map.on('zoomend',()=>document.querySelector('.reset-map-control')?.classList.toggle('visible',map.getZoom()>overviewZoom));
}
function renderMap(data){
  initMap(); if(!markers)return; visibleForMap=data;markers.clearLayers(); const bounds=[];
  data.forEach(p=>{const gp=p.address?.geopoint;if(!gp||gp.length<2)return;const latlng=[gp[1],gp[0]],icon=L.divIcon({html:`<span class="map-price">${money(p.marketRent?.amount).replace('.00','')}</span>`});L.marker(latlng,{icon}).addTo(markers).bindPopup(mapPreview(p),{className:'property-map-popup',minWidth:340,maxWidth:360,autoPanPadding:[24,24]});if(latlng[0]>=30&&latlng[0]<=32.5&&latlng[1]>=-99&&latlng[1]<=-96)bounds.push(latlng)});
  if(bounds.length){map.fitBounds(bounds,{padding:[45,45],maxZoom:12});overviewZoom=map.getZoom()}else{map.setView([31.55,-97.15],10);overviewZoom=10}
}
function fitAllHomes(){document.querySelector('.reset-map-control')?.classList.remove('visible');const bounds=[];visibleForMap.forEach(p=>{const g=p.address?.geopoint;if(g&&g[1]>=30&&g[1]<=32.5&&g[0]>=-99&&g[0]<=-96)bounds.push([g[1],g[0]])});if(bounds.length)map.fitBounds(bounds,{padding:[45,45],maxZoom:12});else map.setView([31.55,-97.15],10)}
function showDetails(id){const p=listings.find(x=>x._id===id);if(!p)return;const img=p.marketingFiles?.[0]||p.photo?.[0]||'assets/areas.jpg';$('#detailContent').innerHTML=`<img class="detail-photo" src="${esc(img)}" alt="${esc(street(p))}"><div class="detail-copy"><p class="eyebrow blue">AVAILABLE NOW</p><h2>${esc(street(p))}</h2><p><b>${money(p.marketRent?.amount)}/mo · ${esc(p.beds)} bd · ${esc(p.baths)} ba · ${p.totalArea?Number(p.totalArea).toLocaleString():'—'} sq ft</b></p><p>${esc(p.marketingDescription||'Contact J R Grace Realty for more information about this home.')}</p><a class="primary" href="${esc(applyUrl(p))}" target="_blank" rel="noopener">Apply through Aptly</a></div>`;$('#details').showModal()}

async function load(){try{const response=await fetch(API);if(!response.ok)throw new Error(`Feed returned ${response.status}`);const json=await response.json();listings=(json.data||[]).filter(p=>p.publishedForRent!==false);$('#heroCount').textContent=listings.length;const types=[...new Set(listings.map(p=>p.rentalCategory).filter(Boolean))].sort();$('#type').insertAdjacentHTML('beforeend',types.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join(''));render()}catch(error){document.querySelector('.results-split')?.classList.remove('loading');$('#status').classList.add('error-state');$('#status').innerHTML=`<div class="error"><h3>Current listings are temporarily unavailable.</h3><p><a href="${APTLY_SEARCH}">Open the JR Grace Aptly search</a></p></div>`;console.error(error)}}
document.querySelectorAll('#query,#rent,#beds,#type').forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',render));
$('#clear').addEventListener('click',()=>{$('#query').value='';$('#rent').value='';$('#beds').value='';$('#type').value='';render()});
$('#filtersToggle').addEventListener('click',()=>{$('#advancedFilters').classList.toggle('open');$('#filtersToggle span').textContent=$('#advancedFilters').classList.contains('open')?'−':'＋'});
function photos(p){return p.marketingFiles?.length?p.marketingFiles:(p.photo||[])}
function updateCompare(){const items=[...compared].map(id=>listings.find(p=>p._id===id)).filter(Boolean);$('#compareTray').hidden=!items.length;$('#compareCount').textContent=items.length;$('#compareNames').textContent=items.map(street).join(' · ')}
function toggleCompare(id){if(compared.has(id))compared.delete(id);else if(compared.size<3)compared.add(id);updateCompare();render()}
function compareRow(label,value){return `<div class="compare-row"><span>${esc(label)}</span><b>${esc(value??'Contact leasing')}</b></div>`}
function showComparison(){const items=[...compared].map(id=>listings.find(p=>p._id===id)).filter(Boolean);if(!items.length)return;$('#compareContent').innerHTML=`<div class="compare-heading"><p class="eyebrow blue">SIDE BY SIDE</p><h2>Compare homes</h2></div><div class="comparison-grid">${items.map((p,i)=>{const imgs=photos(p),addr=`${p.address?.city}, ${p.address?.stateCode}, ${p.address?.postalCode}`;return `<article class="compare-property" data-id="${esc(p._id)}" data-photo="0"><div class="compare-media"><img src="${esc(imgs[0]||'assets/areas.jpg')}" alt="${esc(street(p))}"><span class="compare-badge">● AVAILABLE NOW</span>${imgs.length>1?'<button class="cmp-arrow cmp-prev">‹</button><button class="cmp-arrow cmp-next">›</button>':''}<span class="cmp-count"><b>1</b> / ${imgs.length||1}</span></div><div class="compare-intro"><h3>${esc(street(p))}</h3><p>${esc(addr)}</p><div class="compare-actions"><a href="${esc(tourUrl(p))}" target="_blank" rel="noopener">SELF TOUR</a><button class="cmp-share">SHARE</button><a href="rental-detail.html?id=${encodeURIComponent(p._id)}">VIEW DETAILS</a></div></div><div class="gold-rule"></div><div class="compare-specs">${compareRow('Monthly rent',money(p.marketRent?.amount))}${compareRow('Bedrooms',p.beds)}${compareRow('Bathrooms',p.baths)}${compareRow('Square feet',p.totalArea?Number(p.totalArea).toLocaleString():'—')}${compareRow('Availability','Available now')}${compareRow('Lease term','Contact leasing')}${compareRow('Pets',p.petsAllowed?'Allowed; restrictions may apply':'Contact leasing')}${compareRow('Security deposit',money(p.deposit?.amount))}${compareRow('Application fee','Contact leasing')}${compareRow('Laundry',p.laundryType||'Contact leasing')}${compareRow('Parking',p.parkingType||'Contact leasing')}</div><div class="compare-section"><h4>AMENITIES</h4><p>${esc(p.buildingType||p.rentalCategory||'Contact JR Grace Realty for amenity details.')}</p></div><div class="compare-section compare-location"><h4>LOCATION</h4><p>${esc(p.address?.formattedAddress||p.address?.standardAddress||addr)}</p><div class="compare-map" id="compare-map-${i}"></div></div></article>`}).join('')}</div>`;$('#compareDialog').showModal();items.forEach((p,i)=>{const g=p.address?.geopoint;if(!g||!window.L)return;const m=L.map(`compare-map-${i}`,{zoomControl:true,scrollWheelZoom:false,dragging:true}).setView([g[1],g[0]],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(m);L.marker([g[1],g[0]]).addTo(m)})}
$('#listingGrid').addEventListener('click',async e=>{const card=e.target.closest('.property-card');if(!card)return;const p=listings.find(x=>x._id===card.dataset.id);if(!p)return;if(e.target.closest('.photo-arrow')){e.preventDefault();const arr=photos(p);let n=Number(card.dataset.photo||0)+(e.target.closest('.photo-next')?1:-1);n=(n+arr.length)%arr.length;card.dataset.photo=n;const image=card.querySelector('.media img'),status=card.querySelector('.photo-count');image.src=arr[n];image.alt=`${street(p)}, photo ${n+1} of ${arr.length}`;status.innerHTML=photoStatus(n,arr.length);status.setAttribute('aria-label',`Photo ${n+1} of ${arr.length}`);return}if(e.target.closest('.compare-button')){e.preventDefault();toggleCompare(p._id);return}const share=e.target.closest('.share-button');if(share){e.preventDefault();const url=new URL(`rental-detail.html?id=${encodeURIComponent(p._id)}`,location.href).href;try{if(navigator.share)await navigator.share({title:street(p),text:`${street(p)} — ${money(p.marketRent?.amount)}/mo`,url});else{await navigator.clipboard.writeText(url);share.querySelector('span').textContent='COPIED';setTimeout(()=>share.querySelector('span').textContent='SHARE',1400)}}catch{}}});
$('#map').addEventListener('click',e=>{const arrow=e.target.closest('.map-photo-arrow');if(!arrow)return;e.preventDefault();e.stopPropagation();const preview=arrow.closest('.map-property-preview'),p=listings.find(x=>x._id===preview?.dataset.id);if(!p)return;const imgs=photos(p);let n=Number(preview.dataset.photo||0)+(arrow.classList.contains('map-photo-next')?1:-1);n=(n+imgs.length)%imgs.length;preview.dataset.photo=n;const image=preview.querySelector('.map-preview-media img'),status=preview.querySelector('.map-photo-status');image.src=imgs[n];image.alt=`${street(p)}, photo ${n+1} of ${imgs.length}`;status.innerHTML=photoStatus(n,imgs.length);status.setAttribute('aria-label',`Photo ${n+1} of ${imgs.length}`)});
$('#clearCompare').addEventListener('click',()=>{compared.clear();updateCompare();render()});$('#viewCompare').addEventListener('click',showComparison);$('.compare-close').addEventListener('click',()=>$('#compareDialog').close());
$('#compareContent').addEventListener('click',async e=>{const col=e.target.closest('.compare-property');if(!col)return;const p=listings.find(x=>x._id===col.dataset.id);if(!p)return;if(e.target.closest('.cmp-arrow')){const imgs=photos(p);let n=Number(col.dataset.photo||0)+(e.target.closest('.cmp-next')?1:-1);n=(n+imgs.length)%imgs.length;col.dataset.photo=n;col.querySelector('.compare-media img').src=imgs[n];col.querySelector('.cmp-count b').textContent=n+1;return}if(e.target.closest('.cmp-share')){const url=new URL(`rental-detail.html?id=${encodeURIComponent(p._id)}`,location.href).href;try{if(navigator.share)await navigator.share({title:street(p),url});else{await navigator.clipboard.writeText(url);e.target.textContent='COPIED'}}catch{}}});
const requestedCity=new URLSearchParams(location.search).get('city');if(requestedCity)$('#query').value=requestedCity;
$('#details .close').addEventListener('click',()=>$('#details').close());
$('.menu').addEventListener('click',()=>document.querySelector('header nav').classList.toggle('open'));
load();
