const API='https://app.getaptly.com/api/portal/listings/yDgjRcz9hTcv4iav4';
const CONTEXT_API='https://app.getaptly.com/api/portal/context/';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((c||0)/100);
const id=new URLSearchParams(location.search).get('id');
const zones={'US/Eastern':'America/New_York','US/Central':'America/Chicago','US/Mountain':'America/Denver','US/Pacific':'America/Los_Angeles','US/Arizona':'America/Phoenix','US/Alaska':'America/Anchorage','US/Hawaii':'Pacific/Honolulu'};
const zoneLabels={'US/Eastern':'Eastern Time','US/Central':'Central Time','US/Mountain':'Mountain Time','US/Pacific':'Pacific Time','US/Arizona':'Arizona Time','US/Alaska':'Alaska Time','US/Hawaii':'Hawaii Time'};
let galleryPhotos=[],viewerIndex=0;

function street(p){return p.address?.address||p.marketingName||p.name}
function feedUrl(){return[...arguments].find(v=>typeof v==='string'&&/^https:\/\//.test(v))}
function tour(p){return feedUrl(p.aptlyShowings?.link,p.aptlyShowings?.url,p.links?.tour,p.tourUrl)||(p.aptlyShowings?.active&&p.companyId&&p._id?`https://portal.getaptly.com/${encodeURIComponent(p.companyId)}/showing/app/showing/create/?cId=${encodeURIComponent(p._id)}`:'https://portal.getaptly.com/search/yDgjRcz9hTcv4iav4/')}
function apply(p){return feedUrl(p.aptlyScreening?.link,p.links?.apply,p.applyUrl)||'https://portal.getaptly.com/search/yDgjRcz9hTcv4iav4/'}

function setMeta(selector,value,attribute='content'){const node=$(selector);if(node&&value)node.setAttribute(attribute,value)}
function injectSeo(p,pics,type){
  const address=p.address||{},formatted=address.formattedAddress||address.standardAddress||street(p),rent=money(p.marketRent?.amount),title=`${p.beds}-Bedroom ${type} for Rent in ${address.city}, ${address.stateCode} | J R Grace Realty`,description=`${formatted}: ${p.beds} bedroom, ${p.baths} bathroom ${String(type).toLowerCase()} for rent at ${rent} per month${p.totalArea?` with ${Number(p.totalArea).toLocaleString()} square feet`:''}. View photos, features, tour times, nearby schools, and application details.`.slice(0,300),canonical=`https://jr-grace-realty-review.sshekou.chatgpt.site/rental-detail.html?id=${encodeURIComponent(p._id)}`,image=pics[0];
  document.title=title;setMeta('#seoDescription',description);setMeta('#ogTitle',title);setMeta('#ogDescription',description);setMeta('#ogUrl',canonical);setMeta('#twitterTitle',title);setMeta('#twitterDescription',description);setMeta('#canonicalUrl',canonical,'href');if(image)setMeta('#ogImage',image);
  const pets=p.petsAllowed?'Pets are allowed; restrictions and pet charges may apply.':'Contact J R Grace Realty to confirm the current pet policy.',tourAnswer=p.aptlyShowings?.active?'Yes. Available self-tour windows are loaded from Aptly on this page and confirmed during reservation.':'Contact J R Grace Realty for the current showing options.',faqs=[
    [`How much is the monthly rent for ${street(p)}?`,`${rent} per month is the current advertised base rent. Final lease terms and conditional fees control.`],
    [`How many bedrooms and bathrooms does this rental have?`,`${street(p)} has ${p.beds} bedroom${Number(p.beds)===1?'':'s'} and ${p.baths} bathroom${Number(p.baths)===1?'':'s'}${p.totalArea?`, with approximately ${Number(p.totalArea).toLocaleString()} square feet`:''}.`],
    [`Can I schedule a tour of ${street(p)}?`,tourAnswer],
    [`Are pets allowed at ${street(p)}?`,pets]
  ];
  $('#listingFaq').innerHTML=faqs.map(([question,answer],i)=>`<details${i===0?' open':''}><summary>${esc(question)}</summary><p>${esc(answer)}</p></details>`).join('');
  const coords=listingCoordinates(p),schema={'@context':'https://schema.org','@graph':[{'@type':'RealEstateListing','@id':`${canonical}#listing`,name:title,url:canonical,description,datePosted:p.createdAt||undefined,image:pics.slice(0,10),offers:{'@type':'Offer',price:Number(p.marketRent?.amount||0)/100,priceCurrency:'USD',availability:'https://schema.org/InStock',url:apply(p)},mainEntity:{'@type':/apartment/i.test(type)?'Apartment':'SingleFamilyResidence',name:formatted,address:{'@type':'PostalAddress',streetAddress:address.address,addressLocality:address.city,addressRegion:address.stateCode,postalCode:address.postalCode,addressCountry:'US'},geo:coords?{'@type':'GeoCoordinates',latitude:coords.lat,longitude:coords.lon}:undefined,numberOfBedrooms:p.beds,numberOfBathroomsTotal:p.baths,floorSize:p.totalArea?{'@type':'QuantitativeValue',value:Number(p.totalArea),unitCode:'FTK'}:undefined,petsAllowed:p.petsAllowed}},{'@type':'FAQPage',mainEntity:faqs.map(([question,answer])=>({'@type':'Question',name:question,acceptedAnswer:{'@type':'Answer',text:answer}}))}]};
  $('#listingStructuredData')?.remove();const script=document.createElement('script');script.type='application/ld+json';script.id='listingStructuredData';script.textContent=JSON.stringify(schema);document.head.appendChild(script);
}

function renderGallery(p,pics){
  galleryPhotos=pics;const visible=pics.slice(0,5),remaining=Math.max(0,pics.length-5);
  $('#gallery').innerHTML=visible.map((src,i)=>`<button class="gallery-photo gallery-photo-${i+1}" data-photo="${i}" aria-label="Open photo ${i+1} of ${pics.length}"><img src="${esc(src)}" alt="${esc(p.address?.formattedAddress||street(p))} rental property photo ${i+1}">${i===4&&remaining?`<span class="more-photos">+${remaining} photos</span>`:''}</button>`).join('');
  $('#viewerThumbs').innerHTML=pics.map((src,i)=>`<button data-viewer-photo="${i}" aria-label="View photo ${i+1}"><img loading="lazy" src="${esc(src)}" alt=""></button>`).join('');
  $('#viewerTitle').textContent=street(p);
}
function showViewer(index){viewerIndex=(index+galleryPhotos.length)%galleryPhotos.length;const viewer=$('#photoViewer'),image=viewer.querySelector('figure img');image.src=galleryPhotos[viewerIndex];image.alt=`Property photo ${viewerIndex+1} of ${galleryPhotos.length}`;$('#viewerCount').textContent=`${viewerIndex+1} / ${galleryPhotos.length}`;viewer.querySelectorAll('[data-viewer-photo]').forEach((button,i)=>button.classList.toggle('active',i===viewerIndex));viewer.querySelector(`[data-viewer-photo="${viewerIndex}"]`)?.scrollIntoView({inline:'center',block:'nearest'});if(!viewer.open)viewer.showModal()}
$('#gallery').addEventListener('click',e=>{const button=e.target.closest('[data-photo]');if(button)showViewer(Number(button.dataset.photo))});
$('#photoViewer').addEventListener('click',e=>{if(e.target.closest('.viewer-close'))return $('#photoViewer').close();if(e.target.closest('.viewer-prev'))return showViewer(viewerIndex-1);if(e.target.closest('.viewer-next'))return showViewer(viewerIndex+1);const thumb=e.target.closest('[data-viewer-photo]');if(thumb)return showViewer(Number(thumb.dataset.viewerPhoto));if(e.target===$('#photoViewer'))$('#photoViewer').close()});
document.addEventListener('keydown',e=>{if(!$('#photoViewer').open)return;if(e.key==='ArrowLeft')showViewer(viewerIndex-1);if(e.key==='ArrowRight')showViewer(viewerIndex+1)});

function localParts(date,timeZone){const parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),n=type=>Number(parts.find(x=>x.type===type)?.value||0);return{year:n('year'),month:n('month'),day:n('day'),hour:n('hour'),minute:n('minute')}}
function formatTime(value){const hour=Math.floor(value/100),minute=value%100;return new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',timeZone:'UTC'}).format(new Date(Date.UTC(2020,0,1,hour,minute)))}
function tourIso(dateKey,value,timeZone){const hour=String(Math.floor(value/100)).padStart(2,'0'),minute=String(value%100).padStart(2,'0'),offset=(new Intl.DateTimeFormat('en-US',{timeZone,timeZoneName:'longOffset'}).formatToParts(new Date(`${dateKey}T12:00:00Z`)).find(x=>x.type==='timeZoneName')?.value||'GMT+00:00').replace('GMT','')||'+00:00';return new Date(`${dateKey}T${hour}:${minute}:00${offset}`).toISOString()}
function tourDays(calendar){
  const zoneKey=calendar?.businessHours?.timezone,duration=Number(calendar?.tourDurationMin);
  if(!zoneKey||!Number.isFinite(duration)||duration<=0||!calendar?.multiTimeRanges)return null;
  const timeZone=zones[zoneKey]||zoneKey,now=localParts(new Date(),timeZone),today=`${now.year}-${String(now.month).padStart(2,'0')}-${String(now.day).padStart(2,'0')}`,anchor=new Date(Date.UTC(now.year,now.month-1,now.day,12)),days=[];
  for(let offset=0;offset<6;offset++){const date=new Date(anchor);date.setUTCDate(date.getUTCDate()+offset);const dateKey=date.toISOString().slice(0,10),range=calendar?.multiTimeRanges?.[String(date.getUTCDay())];if(!range?.active)continue;const times=[];for(const slot of range.slots||[]){let cursor=Math.floor(slot.startTime/100)*60+slot.startTime%100,end=Math.floor(slot.endTime/100)*60+slot.endTime%100;while(cursor<end){const value=Math.floor(cursor/60)*100+cursor%60;if(dateKey!==today||value>now.hour*100+now.minute)times.push(value);cursor+=duration}}if(times.length)days.push({date,dateKey,offset,times})}
  return{days,zoneKey,timeZone};
}
function renderTours(p,context){
  const listingCalendar=context?.aptlyListings?.overrideCalendarEnabled?context.aptlyListings.overrideCalendar:context?.aptlyListings?.defaultCalendar;
  const companyListings=context?.companyInfo?.aptlyListings||{},calendar=listingCalendar||companyListings.defaultCalendar,enabled=p.aptlyShowings?.active&&calendar?.multiTimeRanges;
  const scheduler=$('#tourScheduler'),booking=tour(p);
  if(!enabled){scheduler.innerHTML=`<p class="tour-unavailable">Aptly is not currently publishing self-tour times for this home.</p><a class="gold-button" href="${esc(booking)}" target="_blank" rel="noopener">CHECK TOUR AVAILABILITY</a>`;return}
  const schedule=tourDays(calendar),days=schedule?.days||[];if(!schedule||!days.length){scheduler.innerHTML=`<p class="tour-unavailable">Aptly does not currently show an upcoming self-tour window for this home. Please check again later.</p><a class="gold-button" href="${esc(booking)}" target="_blank" rel="noopener">CHECK APTLY</a>`;return}
  let chosenDay=0,chosenTime=null;
  const draw=()=>{const selected=days[chosenDay];scheduler.innerHTML=`<div class="tour-days" role="tablist" aria-label="Tour dates published by Aptly">${days.slice(0,5).map((day,i)=>`<button role="tab" aria-selected="${i===chosenDay}" class="${i===chosenDay?'is-selected':''}" data-tour-day="${i}"><span>${day.offset===0?'Today':day.offset===1?'Tomorrow':new Intl.DateTimeFormat('en-US',{weekday:'short',timeZone:'UTC'}).format(day.date)}</span><strong>${new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(day.date)}</strong></button>`).join('')}</div><p class="tour-time-note">Scheduling windows are loaded directly from Aptly. Final availability is confirmed when you reserve. Times shown in ${zoneLabels[schedule.zoneKey]||schedule.zoneKey}.</p><div class="tour-times">${selected.times.map(time=>`<button class="${time===chosenTime?'is-selected':''}" data-tour-time="${time}">${formatTime(time)}</button>`).join('')}</div><a class="gold-button tour-continue ${chosenTime==null?'is-disabled':''}" ${chosenTime==null?'aria-disabled="true"':`href="${esc(booking)}&tourDate=${encodeURIComponent(tourIso(selected.dateKey,chosenTime,schedule.timeZone))}" target="_blank" rel="noopener"`}>${chosenTime==null?'SELECT A TOUR TIME':`CONTINUE WITH ${formatTime(chosenTime)}`}</a>`};
  scheduler.addEventListener('click',e=>{const day=e.target.closest('[data-tour-day]');if(day){chosenDay=Number(day.dataset.tourDay);chosenTime=null;draw();return}const time=e.target.closest('[data-tour-time]');if(time){chosenTime=Number(time.dataset.tourTime);draw()}const disabled=e.target.closest('.tour-continue.is-disabled');if(disabled)e.preventDefault()});draw();
}

function listingCoordinates(p){
  const point=p.address?.geopoint;
  if(Array.isArray(point)&&point.length>=2){const lon=Number(point[0]),lat=Number(point[1]);if(Number.isFinite(lat)&&Number.isFinite(lon))return{lat,lon}}
  const lat=Number(point?.lat??point?.latitude??p.address?.lat??p.address?.latitude),lon=Number(point?.lon??point?.lng??point?.longitude??p.address?.lon??p.address?.lng??p.address?.longitude);
  return Number.isFinite(lat)&&Number.isFinite(lon)?{lat,lon}:null;
}
async function renderSchools(p){
  const coords=listingCoordinates(p),list=$('#schoolList');
  if(!coords||typeof L==='undefined'){list.innerHTML='<div class="school-empty"><p>School mapping is not available for this listing.</p></div>';return}
  try{
    const response=await fetch(`/api/nearby-schools?lat=${encodeURIComponent(coords.lat)}&lon=${encodeURIComponent(coords.lon)}`),data=await response.json().catch(()=>({}));
    if(!response.ok)throw new Error(data.message||'Schools unavailable');
    const schools=Array.isArray(data.schools)?data.schools:[];
    if(!schools.length){list.innerHTML='<div class="school-empty"><p>No nearby schools were returned for this location.</p></div>';return}
    const map=L.map('schoolMap',{scrollWheelZoom:false}).setView([coords.lat,coords.lon],12);
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
    const homeIcon=L.divIcon({className:'home-map-marker',html:'<span class="home-pin" aria-hidden="true">★</span>',iconSize:[42,42],iconAnchor:[21,21]});
    L.marker([coords.lat,coords.lon],{icon:homeIcon,zIndexOffset:1000}).addTo(map).bindPopup(`<b>${esc(street(p))}</b><span>Rental home location</span>`);const bounds=L.latLngBounds([[coords.lat,coords.lon]]);
    const legend=L.control({position:'bottomleft'});
    legend.onAdd=()=>{const node=L.DomUtil.create('div','school-map-legend');node.innerHTML='<span><i class="legend-home" aria-hidden="true">★</i> Rental home</span><span><i class="legend-school" aria-hidden="true">1</i> Nearby school</span>';return node};
    legend.addTo(map);
    list.innerHTML=schools.map((school,i)=>`<a class="school-card" href="${esc(school.url||'#')}" ${school.url?'target="_blank" rel="noopener"':''} data-school="${i}"><span class="school-number">${i+1}</span><span><h3>${esc(school.name)}</h3><p class="school-meta">${esc(school.type)} · ${esc(school.grades)} · ${Number(school.distance).toFixed(1)} mi</p><p class="school-address">${esc(school.address)}</p>${school.ratingBand?`<span class="school-band">${esc(school.ratingBand)}</span>`:''}</span></a>`).join('');
    const markers=schools.map((school,i)=>{const marker=L.marker([school.lat,school.lon],{icon:L.divIcon({className:'school-map-marker',html:`<span class="school-pin">${i+1}</span>`,iconSize:[30,30],iconAnchor:[15,15]})}).addTo(map).bindPopup(`<b>${esc(school.name)}</b><span>${esc(school.grades)} · ${Number(school.distance).toFixed(1)} mi</span>${school.url?`<br><a href="${esc(school.url)}" target="_blank" rel="noopener">School details</a>`:''}`);bounds.extend([school.lat,school.lon]);return marker});
    list.addEventListener('mouseover',event=>{const card=event.target.closest('[data-school]');if(card)markers[Number(card.dataset.school)]?.openPopup()});
    map.fitBounds(bounds.pad(.12),{maxZoom:14,padding:[32,32]});setTimeout(()=>map.invalidateSize(),50);
  }catch(error){$('#nearbySchools').classList.add('schools-unavailable');list.innerHTML=`<div class="school-empty"><b>Nearby school information is not available yet.</b><p>${esc(error.message||'We are finishing the secure school-data connection for this feature.')}</p></div>`}
}

function render(p,all,context){
  const pics=p.marketingFiles?.length?p.marketingFiles:p.photo||[];document.title=`${street(p)}, ${p.address?.city}, TX for Rent | J R Grace Realty`;$('#crumbCity').textContent=`${p.address?.city}, ${p.address?.stateCode}`;$('#crumbStreet').textContent=street(p);renderGallery(p,pics);renderTours(p,context);$('#kicker').textContent=`AVAILABLE RENTAL IN ${(p.address?.city||'WACO').toUpperCase()}, ${p.address?.stateCode||'TX'}`;const type=p.buildingType||p.rentalCategory||'Home';$('#title').textContent=`${p.beds}-Bedroom ${type} for Rent in ${p.address?.city}, ${p.address?.stateCode}`;$('#address').textContent=p.address?.formattedAddress||p.address?.standardAddress;$('#summary').textContent=`${street(p)} is an available ${p.beds}-bedroom, ${p.baths}-bathroom ${type.toLowerCase()} for rent in ${p.address?.city}, ${p.address?.stateCode} ${p.address?.postalCode}. The advertised rent is ${money(p.marketRent?.amount)} per month${p.totalArea?` for approximately ${Number(p.totalArea).toLocaleString()} square feet`:''}.`;$('#rent').textContent=money(p.marketRent?.amount);$('#beds').textContent=p.beds??'—';$('#baths').textContent=p.baths??'—';$('#area').textContent=p.totalArea?Number(p.totalArea).toLocaleString():'—';$('#features').innerHTML=[['PROPERTY TYPE',type],['ADDRESS',p.address?.formattedAddress],['PETS',p.petsAllowed?'Pets allowed':'Contact leasing'],['PARKING',p.parkingType||'Contact leasing'],['LAUNDRY',p.laundryType||'Contact leasing'],['DEPOSIT',money(p.deposit?.amount)]].map(x=>`<div><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('');$('#aboutHeading').textContent=`About this ${p.address?.city} rental`;$('#description').textContent=p.marketingDescription||'Contact JR Grace Realty for details about this available home.';$('#costRent').textContent=$('#baseRent').textContent=money(p.marketRent?.amount);$('#deposit').textContent=money(p.deposit?.amount);['tourSide','tourBottom'].forEach(x=>$('#'+x).href='#tour-times');['applySide','applyBottom'].forEach(x=>$('#'+x).href=apply(p));const similar=all.filter(x=>x._id!==p._id&&(x.address?.city===p.address?.city||x.beds===p.beds)).slice(0,3);$('#similar').innerHTML=similar.map(x=>`<article class="similar-card"><a href="rental-detail.html?id=${encodeURIComponent(x._id)}"><img src="${esc(x.marketingFiles?.[0]||x.photo?.[0]||'assets/areas.jpg')}" alt="${esc(street(x))}"><div><b>${money(x.marketRent?.amount)}/mo</b><p>${x.beds} bd · ${x.baths} ba · ${x.totalArea?Number(x.totalArea).toLocaleString():'—'} sq ft</p><h3>${esc(street(x))}</h3><span>${esc(x.address?.city)}, ${esc(x.address?.stateCode)} ${esc(x.address?.postalCode)}</span></div></a></article>`).join('');$('#loading').hidden=true;$('#page').hidden=false;renderSchools(p);
}

Promise.all([fetch(API).then(r=>r.ok?r.json():Promise.reject()),fetch(`${CONTEXT_API}${encodeURIComponent(id)}?audience=showing`).then(r=>r.ok?r.json():null).catch(()=>null)]).then(([j,context])=>{const all=j.data||[],p=all.find(x=>x._id===id);if(p){render(p,all,context);$('#loading')?.remove();const pics=p.marketingFiles?.length?p.marketingFiles:p.photo||[],type=p.buildingType||p.rentalCategory||'Home';injectSeo(p,pics,type)}else throw new Error('not found')}).catch(()=>{$('#loading')?.remove();$('#unavailable').hidden=false});
