// Auto-generated by Aptly — do not edit manually
export const site = {
  companyName: "J R Grace Realty",
  logoPath: "https://preview.getaptly.com/cdn/storage/AptlyFiles/FwMBFExugJG7nvPzq/original/FwMBFExugJG7nvPzq.png",
  // Used at build time to fetch this company's public listings feed and generate
  // a real static page per rental (src/pages/rentals/[id].astro).
  companyId: "yDgjRcz9hTcv4iav4",
  listingsWidgetUrl: "https://portal.getaptly.com/search/yDgjRcz9hTcv4iav4",
  tagline: "",
  description: "",
  phone: "(254) 777-5577",
  email: "hello@jrgrace.com",
  address: "2012 Lake Air Dr. Suite F, Waco, TX, 76710",
  colors: {
    primary: "#2f6df6",
    primaryDark: '#1a56db',
    bg: '#f7f8fb',
    surface: '#ffffff',
    ink: '#161b26',
    muted: '#7a8395',
    accent: "#b7a064",
    accentInk: '#142337',
  },
  nav: [
    { label: 'Services', href: '#services' },
    { label: 'Rental Search', href: '/rentals' },
    
    { label: 'About', href: '#about' },
    { label: 'Testimonials', href: '#testimonials' },
    { label: 'Contact', href: '#contact' },
    
  ],
  hero: {
    headline: 'Professional Property Management',
    subheadline: "We handle everything so you can enjoy your investment.",
    cta: 'Get a Free Consultation',
    ctaHref: '#contact',
  },
  services: [
    { icon: '🏠', title: 'Leasing & Marketing', description: 'Professional photography, syndicated listings, and thorough tenant screening.' },
    { icon: '🔧', title: 'Maintenance & Repairs', description: '24/7 emergency response and a trusted vendor network.' },
    { icon: '💰', title: 'Rent Collection', description: 'Automated collection, owner disbursements, and detailed monthly statements.' },
    { icon: '📊', title: 'Financial Reporting', description: 'Real-time owner portal with income/expense reports and full transaction history.' },
    { icon: '⚖️', title: 'Legal Compliance', description: 'Stay current with local landlord-tenant law, lease enforcement, and eviction management.' },
    { icon: '🤝', title: 'Tenant Relations', description: 'Responsive communication and move-in/move-out inspections.' },
  ],
  stats: [
    { value: '500+', label: 'Properties Managed' },
    { value: '10+', label: 'Years in Business' },
    { value: '98%', label: 'Occupancy Rate' },
    { value: '4.9★', label: 'Owner Rating' },
  ],
  about: {
    headline: 'Locally Owned. Owner Focused.',
    body: "We built the company we wished existed — one that treats every property like our own.",
    points: [
      'Licensed with full fiduciary responsibility',
      'Dedicated owner portal with real-time reporting',
      'Fast turnaround on maintenance requests',
      'No hidden fees — flat rate management only',
    ],
  },
  testimonials: [
    { quote: 'Best property manager we have ever worked with.', author: 'Michael T.', detail: 'Owner of 4 properties' },
    { quote: 'They filled my vacancy in 11 days. Communication is always fast.', author: 'Sarah K.', detail: 'Duplex owner' },
    { quote: 'Finally a property manager who picks up the phone.', author: 'James R.', detail: 'Commercial property investor' },
  ],
  contact: {
    headline: 'Ready to Get Started?',
    subheadline: 'Get a free rental analysis and management proposal within 24 hours.',
  },
  seo: {
    title: "J R Grace Realty | Professional Property Management",
    description: "Professional property management services.",
    ogImage: '/images/og.jpg',
  },
  social: { facebook: '', instagram: '', linkedin: '' },
  // Populated only by the Designer AI chat editing config.ts directly (see ai.js) — there's no
  // UI field for this. Like services/testimonials/hero copy, a full deploy/reset regenerates
  // this from aptlySite, which never actually stores it, so AI-added areas don't survive a
  // full redeploy today — a known, already-accepted limitation for AI-authored structured
  // content in general, not new to this field.
  areas: [],
};